import Blogs from "@/components/Blogs";
import React from "react";
export const blogData = [
  {
    id: 1,
    title: "Claim Your coin in claim Rocket ",
    author: "Al Amin Khan",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt lacus neque, et dictum nibh porttitor ac. Quisque eros turpis, sodales ut lacus sit amet, dictum condimentum ligula. Nam luctus sem a ex euismod elementum. Integer malesuada magna at leo dapibus molestie. In dignissim mauris eget lectus dapibus tincidunt. Nunc eleifend laoreet ligula nec pharetra. Pellentesque iaculis nulla elit, id fringilla est faucibus eu. Nam purus neque, pulvinar quis lorem ut, commodo rhoncus urna. Sed semper nunc nec erat tristique viverra.

Aenean hendrerit ac turpis non varius. Maecenas tristique arcu turpis, sed volutpat neque feugiat vitae. Vivamus ac mi consequat, vulputate purus nec, maximus tortor. Vivamus eget convallis ex. Ut bibendum vel arcu quis posuere. Pellentesque quis sem felis. Nullam ac massa et felis auctor gravida a ac ex. Integer ornare, nisl et volutpat dignissim, felis odio malesuada augue, nec interdum nulla diam a arcu. Phasellus et finibus lorem. Phasellus maximus consequat mauris, et pharetra sapien malesuada non. Nulla lobortis dui ut blandit consectetur. Aenean vel diam nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque commodo rhoncus tellus, et tempor nibh. Phasellus vel est placerat, malesuada eros vitae, dapibus libero.

Integer in mattis erat, eget ultricies justo. Suspendisse cursus sit amet orci nec gravida. Vestibulum vulputate, ipsum nec sollicitudin molestie, nibh nisl convallis risus, a malesuada ante purus eu nulla. Proin tincidunt tortor vel libero varius blandit. Donec dapibus accumsan tortor, sed blandit sem egestas nec. Praesent nec interdum nisi, at porta nisi. Proin aliquam dictum velit at fermentum. Sed convallis neque nec nibh sodales commodo. Integer eget est vel mauris pretium blandit.

Duis et turpis sit amet odio auctor volutpat non in elit. Sed porttitor, nisl molestie porttitor interdum, diam elit iaculis neque, vitae porttitor sapien nulla et dolor. Nam mollis lobortis nulla vel fermentum. Donec ultricies condimentum felis, a dignissim ligula dictum ac. Nulla eleifend felis justo, ac pellentesque eros luctus eu. Cras vitae ullamcorper sem. Vestibulum vitae suscipit ligula. Ut vitae volutpat dui. Proin tempor urna eleifend neque venenatis, in condimentum velit venenatis. Curabitur non magna molestie, commodo sem in, iaculis ligula. Donec pulvinar pellentesque risus eu gravida. Aenean vel pretium velit.

Cras tincidunt mi vitae congue bibendum. Aliquam molestie justo vitae arcu iaculis, ut egestas lorem maximus. Morbi placerat turpis neque, et auctor neque molestie sit amet. Duis ligula purus, aliquam sit amet faucibus a, luctus ut lorem. In tincidunt ac odio quis tempus. Duis mattis dictum velit, gravida lobortis nulla pharetra non. Curabitur eu ultricies ligula, quis dignissim neque. Cras a molestie metus.

Integer sed ultricies orci, nec suscipit sapien. Duis sit amet magna in risus malesuada ullamcorper sed at elit. Fusce magna odio, efficitur vel pellentesque ac, feugiat nec ex. Integer id volutpat dui, vitae ullamcorper felis. Aliquam porttitor dictum quam, ac dignissim lorem iaculis sit amet. Nulla fringilla condimentum velit. Mauris fermentum malesuada risus eu molestie. Sed vitae libero tempus, pulvinar mi sed, finibus orci. Curabitur congue orci et egestas maximus. Mauris iaculis rhoncus convallis. Suspendisse consectetur arcu quam, a tempor metus vulputate quis. Sed massa odio, finibus eget dolor a, varius elementum ligula. Sed porttitor eu magna nec tempus. Nam eget risus ipsum. Donec bibendum, ligula sit amet hendrerit tincidunt, nunc felis laoreet lectus, scelerisque porta ex dolor quis dui. Fusce a ex luctus, dapibus ex vitae, faucibus mi.

Maecenas mattis, ante a placerat elementum, quam justo elementum ligula, eget hendrerit erat diam id orci. Suspendisse orci lacus, porta sit amet nunc nec, maximus molestie augue. Nam id convallis odio. Vestibulum aliquam, risus at commodo vehicula, risus enim congue metus, nec accumsan mi erat ac risus. Proin ligula quam, feugiat vel elit vel, laoreet elementum nibh. Cras eget cursus velit. Phasellus eget metus augue. Donec consequat, magna vel imperdiet maximus, sapien nibh hendrerit nisi, vitae dignissim erat odio quis dolor. Praesent sagittis cursus tortor sit amet sagittis. Suspendisse erat lacus, laoreet ut viverra quis, porta sed justo. Aliquam erat volutpat. Nullam placerat fermentum enim, a condimentum tortor sollicitudin non. Pellentesque accumsan dictum ligula in mattis.

Praesent blandit consectetur pretium. Etiam aliquam sem nunc, vel interdum massa tincidunt at. Cras a placerat eros. Suspendisse consequat vel arcu eget eleifend. Proin mollis tincidunt lobortis. Sed luctus, libero nec varius mattis, purus dolor porta metus, eget efficitur sem justo sed tellus. Praesent eu urna sed orci elementum luctus. Ut lacinia magna vitae pulvinar tempor. Sed mauris mi, ullamcorper sed ipsum non, fringilla sodales urna. Sed tellus justo, tristique ac interdum at, aliquam at libero. Donec tincidunt semper diam sed finibus. Vestibulum sit amet quam eu nisl venenatis molestie vel at dui. Nulla sed fermentum nisl.

Pellentesque feugiat nec ipsum id facilisis. Etiam rhoncus ligula felis, sollicitudin ultricies erat fringilla non. Cras tempus sed lacus eu gravida. Phasellus at nibh fermentum, feugiat ante sit amet, rutrum mauris. Fusce venenatis ex justo, ac iaculis risus laoreet id. Suspendisse non purus vitae lorem imperdiet scelerisque. Quisque consectetur erat justo, vel facilisis metus accumsan nec. Proin sodales sem nibh, quis eleifend nibh maximus vitae. Etiam scelerisque ante lorem, in laoreet augue eleifend ut. Praesent at sodales risus, at dictum tortor. Aliquam et varius nisl, sit amet ultricies lorem. Sed magna nunc, congue non tellus sit amet, varius tincidunt diam.

Duis malesuada orci arcu, at lacinia enim condimentum sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut consequat metus sed enim accumsan, a ullamcorper nisi aliquam. Integer id est ullamcorper, dictum nibh eget, rutrum magna. Integer dapibus congue aliquam. Duis vehicula tortor in felis suscipit, vel sodales ex tristique. Fusce nec tortor a orci sollicitudin fermentum. Donec venenatis nunc semper est porta dignissim. Praesent id fringilla turpis, sit amet lacinia metus. Fusce egestas, leo lobortis sollicitudin dictum, lorem leo lobortis risus, at maximus urna ante vitae nulla. Integer dictum tortor sapien. Sed consequat dignissim velit. Suspendisse nec dignissim ipsum.`,
    imageUrl:
      "https://qph.cf2.quoracdn.net/main-qimg-fa486befc7f0b2f82f5771e0a77207ad-lq", // Replace with your image path
    date: "September 1, 2023",
  },
  {
    id: 3,
    title: "Know where to find you lawyer",
    author: "Sohag Miya",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt lacus neque, et dictum nibh porttitor ac. Quisque eros turpis, sodales ut lacus sit amet, dictum condimentum ligula. Nam luctus sem a ex euismod elementum. Integer malesuada magna at leo dapibus molestie. In dignissim mauris eget lectus dapibus tincidunt. Nunc eleifend laoreet ligula nec pharetra. Pellentesque iaculis nulla elit, id fringilla est faucibus eu. Nam purus neque, pulvinar quis lorem ut, commodo rhoncus urna. Sed semper nunc nec erat tristique viverra. <br/>

Aenean hendrerit ac turpis non varius. Maecenas tristique arcu turpis, sed volutpat neque feugiat vitae. Vivamus ac mi consequat, vulputate purus nec, maximus tortor. Vivamus eget convallis ex. Ut bibendum vel arcu quis posuere. Pellentesque quis sem felis. Nullam ac massa et felis auctor gravida a ac ex. Integer ornare, nisl et volutpat dignissim, felis odio malesuada augue, nec interdum nulla diam a arcu. Phasellus et finibus lorem. Phasellus maximus consequat mauris, et pharetra sapien malesuada non. Nulla lobortis dui ut blandit consectetur. Aenean vel diam nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque commodo rhoncus tellus, et tempor nibh. Phasellus vel est placerat, malesuada eros vitae, dapibus libero. <br/>

Integer in mattis erat, eget ultricies justo. Suspendisse cursus sit amet orci nec gravida. Vestibulum vulputate, ipsum nec sollicitudin molestie, nibh nisl convallis risus, a malesuada ante purus eu nulla. Proin tincidunt tortor vel libero varius blandit. Donec dapibus accumsan tortor, sed blandit sem egestas nec. Praesent nec interdum nisi, at porta nisi. Proin aliquam dictum velit at fermentum. Sed convallis neque nec nibh sodales commodo. Integer eget est vel mauris pretium blandit. <br/>

Duis et turpis sit amet odio auctor volutpat non in elit. Sed porttitor, nisl molestie porttitor interdum, diam elit iaculis neque, vitae porttitor sapien nulla et dolor. Nam mollis lobortis nulla vel fermentum. Donec ultricies condimentum felis, a dignissim ligula dictum ac. Nulla eleifend felis justo, ac pellentesque eros luctus eu. Cras vitae ullamcorper sem. Vestibulum vitae suscipit ligula. Ut vitae volutpat dui. Proin tempor urna eleifend neque venenatis, in condimentum velit venenatis. Curabitur non magna molestie, commodo sem in, iaculis ligula. Donec pulvinar pellentesque risus eu gravida. Aenean vel pretium velit. <br/>

Cras tincidunt mi vitae congue bibendum. Aliquam molestie justo vitae arcu iaculis, ut egestas lorem maximus. Morbi placerat turpis neque, et auctor neque molestie sit amet. Duis ligula purus, aliquam sit amet faucibus a, luctus ut lorem. In tincidunt ac odio quis tempus. Duis mattis dictum velit, gravida lobortis nulla pharetra non. Curabitur eu ultricies ligula, quis dignissim neque. Cras a molestie metus. <br/>

Integer sed ultricies orci, nec suscipit sapien. Duis sit amet magna in risus malesuada ullamcorper sed at elit. Fusce magna odio, efficitur vel pellentesque ac, feugiat nec ex. Integer id volutpat dui, vitae ullamcorper felis. Aliquam porttitor dictum quam, ac dignissim lorem iaculis sit amet. Nulla fringilla condimentum velit. Mauris fermentum malesuada risus eu molestie. Sed vitae libero tempus, pulvinar mi sed, finibus orci. Curabitur congue orci et egestas maximus. Mauris iaculis rhoncus convallis. Suspendisse consectetur arcu quam, a tempor metus vulputate quis. Sed massa odio, finibus eget dolor a, varius elementum ligula. Sed porttitor eu magna nec tempus. Nam eget risus ipsum. Donec bibendum, ligula sit amet hendrerit tincidunt, nunc felis laoreet lectus, scelerisque porta ex dolor quis dui. Fusce a ex luctus, dapibus ex vitae, faucibus mi. <br/>

Maecenas mattis, ante a placerat elementum, quam justo elementum ligula, eget hendrerit erat diam id orci. Suspendisse orci lacus, porta sit amet nunc nec, maximus molestie augue. Nam id convallis odio. Vestibulum aliquam, risus at commodo vehicula, risus enim congue metus, nec accumsan mi erat ac risus. Proin ligula quam, feugiat vel elit vel, laoreet elementum nibh. Cras eget cursus velit. Phasellus eget metus augue. Donec consequat, magna vel imperdiet maximus, sapien nibh hendrerit nisi, vitae dignissim erat odio quis dolor. Praesent sagittis cursus tortor sit amet sagittis. Suspendisse erat lacus, laoreet ut viverra quis, porta sed justo. Aliquam erat volutpat. Nullam placerat fermentum enim, a condimentum tortor sollicitudin non. Pellentesque accumsan dictum ligula in mattis. <br/>

Praesent blandit consectetur pretium. Etiam aliquam sem nunc, vel interdum massa tincidunt at. Cras a placerat eros. Suspendisse consequat vel arcu eget eleifend. Proin mollis tincidunt lobortis. Sed luctus, libero nec varius mattis, purus dolor porta metus, eget efficitur sem justo sed tellus. Praesent eu urna sed orci elementum luctus. Ut lacinia magna vitae pulvinar tempor. Sed mauris mi, ullamcorper sed ipsum non, fringilla sodales urna. Sed tellus justo, tristique ac interdum at, aliquam at libero. Donec tincidunt semper diam sed finibus. Vestibulum sit amet quam eu nisl venenatis molestie vel at dui. Nulla sed fermentum nisl. <br/>

Pellentesque feugiat nec ipsum id facilisis. Etiam rhoncus ligula felis, sollicitudin ultricies erat fringilla non. Cras tempus sed lacus eu gravida. Phasellus at nibh fermentum, feugiat ante sit amet, rutrum mauris. Fusce venenatis ex justo, ac iaculis risus laoreet id. Suspendisse non purus vitae lorem imperdiet scelerisque. Quisque consectetur erat justo, vel facilisis metus accumsan nec. Proin sodales sem nibh, quis eleifend nibh maximus vitae. Etiam scelerisque ante lorem, in laoreet augue eleifend ut. Praesent at sodales risus, at dictum tortor. Aliquam et varius nisl, sit amet ultricies lorem. Sed magna nunc, congue non tellus sit amet, varius tincidunt diam. <br/>

Duis malesuada orci arcu, at lacinia enim condimentum sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut consequat metus sed enim accumsan, a ullamcorper nisi aliquam. Integer id est ullamcorper, dictum nibh eget, rutrum magna. Integer dapibus congue aliquam. Duis vehicula tortor in felis suscipit, vel sodales ex tristique. Fusce nec tortor a orci sollicitudin fermentum. Donec venenatis nunc semper est porta dignissim. Praesent id fringilla turpis, sit amet lacinia metus. Fusce egestas, leo lobortis sollicitudin dictum, lorem leo lobortis risus, at maximus urna ante vitae nulla. Integer dictum tortor sapien. Sed consequat dignissim velit. Suspendisse nec dignissim ipsum.`,
    imageUrl:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80", // Replace with your image path
    date: "August 25, 2023",
  },
  {
    id: 2,
    title: "Know where to find you lawyer",
    author: "Sohag Miya",
    description: `Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam tincidunt lacus neque, et dictum nibh porttitor ac. Quisque eros turpis, sodales ut lacus sit amet, dictum condimentum ligula. Nam luctus sem a ex euismod elementum. Integer malesuada magna at leo dapibus molestie. In dignissim mauris eget lectus dapibus tincidunt. Nunc eleifend laoreet ligula nec pharetra. Pellentesque iaculis nulla elit, id fringilla est faucibus eu. Nam purus neque, pulvinar quis lorem ut, commodo rhoncus urna. Sed semper nunc nec erat tristique viverra. <br/>

Aenean hendrerit ac turpis non varius. Maecenas tristique arcu turpis, sed volutpat neque feugiat vitae. Vivamus ac mi consequat, vulputate purus nec, maximus tortor. Vivamus eget convallis ex. Ut bibendum vel arcu quis posuere. Pellentesque quis sem felis. Nullam ac massa et felis auctor gravida a ac ex. Integer ornare, nisl et volutpat dignissim, felis odio malesuada augue, nec interdum nulla diam a arcu. Phasellus et finibus lorem. Phasellus maximus consequat mauris, et pharetra sapien malesuada non. Nulla lobortis dui ut blandit consectetur. Aenean vel diam nisi. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Quisque commodo rhoncus tellus, et tempor nibh. Phasellus vel est placerat, malesuada eros vitae, dapibus libero. <br/>

Integer in mattis erat, eget ultricies justo. Suspendisse cursus sit amet orci nec gravida. Vestibulum vulputate, ipsum nec sollicitudin molestie, nibh nisl convallis risus, a malesuada ante purus eu nulla. Proin tincidunt tortor vel libero varius blandit. Donec dapibus accumsan tortor, sed blandit sem egestas nec. Praesent nec interdum nisi, at porta nisi. Proin aliquam dictum velit at fermentum. Sed convallis neque nec nibh sodales commodo. Integer eget est vel mauris pretium blandit. <br/>

Duis et turpis sit amet odio auctor volutpat non in elit. Sed porttitor, nisl molestie porttitor interdum, diam elit iaculis neque, vitae porttitor sapien nulla et dolor. Nam mollis lobortis nulla vel fermentum. Donec ultricies condimentum felis, a dignissim ligula dictum ac. Nulla eleifend felis justo, ac pellentesque eros luctus eu. Cras vitae ullamcorper sem. Vestibulum vitae suscipit ligula. Ut vitae volutpat dui. Proin tempor urna eleifend neque venenatis, in condimentum velit venenatis. Curabitur non magna molestie, commodo sem in, iaculis ligula. Donec pulvinar pellentesque risus eu gravida. Aenean vel pretium velit. <br/>

Cras tincidunt mi vitae congue bibendum. Aliquam molestie justo vitae arcu iaculis, ut egestas lorem maximus. Morbi placerat turpis neque, et auctor neque molestie sit amet. Duis ligula purus, aliquam sit amet faucibus a, luctus ut lorem. In tincidunt ac odio quis tempus. Duis mattis dictum velit, gravida lobortis nulla pharetra non. Curabitur eu ultricies ligula, quis dignissim neque. Cras a molestie metus. <br/>

Integer sed ultricies orci, nec suscipit sapien. Duis sit amet magna in risus malesuada ullamcorper sed at elit. Fusce magna odio, efficitur vel pellentesque ac, feugiat nec ex. Integer id volutpat dui, vitae ullamcorper felis. Aliquam porttitor dictum quam, ac dignissim lorem iaculis sit amet. Nulla fringilla condimentum velit. Mauris fermentum malesuada risus eu molestie. Sed vitae libero tempus, pulvinar mi sed, finibus orci. Curabitur congue orci et egestas maximus. Mauris iaculis rhoncus convallis. Suspendisse consectetur arcu quam, a tempor metus vulputate quis. Sed massa odio, finibus eget dolor a, varius elementum ligula. Sed porttitor eu magna nec tempus. Nam eget risus ipsum. Donec bibendum, ligula sit amet hendrerit tincidunt, nunc felis laoreet lectus, scelerisque porta ex dolor quis dui. Fusce a ex luctus, dapibus ex vitae, faucibus mi. <br/>

Maecenas mattis, ante a placerat elementum, quam justo elementum ligula, eget hendrerit erat diam id orci. Suspendisse orci lacus, porta sit amet nunc nec, maximus molestie augue. Nam id convallis odio. Vestibulum aliquam, risus at commodo vehicula, risus enim congue metus, nec accumsan mi erat ac risus. Proin ligula quam, feugiat vel elit vel, laoreet elementum nibh. Cras eget cursus velit. Phasellus eget metus augue. Donec consequat, magna vel imperdiet maximus, sapien nibh hendrerit nisi, vitae dignissim erat odio quis dolor. Praesent sagittis cursus tortor sit amet sagittis. Suspendisse erat lacus, laoreet ut viverra quis, porta sed justo. Aliquam erat volutpat. Nullam placerat fermentum enim, a condimentum tortor sollicitudin non. Pellentesque accumsan dictum ligula in mattis. <br/>

Praesent blandit consectetur pretium. Etiam aliquam sem nunc, vel interdum massa tincidunt at. Cras a placerat eros. Suspendisse consequat vel arcu eget eleifend. Proin mollis tincidunt lobortis. Sed luctus, libero nec varius mattis, purus dolor porta metus, eget efficitur sem justo sed tellus. Praesent eu urna sed orci elementum luctus. Ut lacinia magna vitae pulvinar tempor. Sed mauris mi, ullamcorper sed ipsum non, fringilla sodales urna. Sed tellus justo, tristique ac interdum at, aliquam at libero. Donec tincidunt semper diam sed finibus. Vestibulum sit amet quam eu nisl venenatis molestie vel at dui. Nulla sed fermentum nisl. <br/>

Pellentesque feugiat nec ipsum id facilisis. Etiam rhoncus ligula felis, sollicitudin ultricies erat fringilla non. Cras tempus sed lacus eu gravida. Phasellus at nibh fermentum, feugiat ante sit amet, rutrum mauris. Fusce venenatis ex justo, ac iaculis risus laoreet id. Suspendisse non purus vitae lorem imperdiet scelerisque. Quisque consectetur erat justo, vel facilisis metus accumsan nec. Proin sodales sem nibh, quis eleifend nibh maximus vitae. Etiam scelerisque ante lorem, in laoreet augue eleifend ut. Praesent at sodales risus, at dictum tortor. Aliquam et varius nisl, sit amet ultricies lorem. Sed magna nunc, congue non tellus sit amet, varius tincidunt diam. <br/>

Duis malesuada orci arcu, at lacinia enim condimentum sed. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Ut consequat metus sed enim accumsan, a ullamcorper nisi aliquam. Integer id est ullamcorper, dictum nibh eget, rutrum magna. Integer dapibus congue aliquam. Duis vehicula tortor in felis suscipit, vel sodales ex tristique. Fusce nec tortor a orci sollicitudin fermentum. Donec venenatis nunc semper est porta dignissim. Praesent id fringilla turpis, sit amet lacinia metus. Fusce egestas, leo lobortis sollicitudin dictum, lorem leo lobortis risus, at maximus urna ante vitae nulla. Integer dictum tortor sapien. Sed consequat dignissim velit. Suspendisse nec dignissim ipsum.`,
    imageUrl:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80", // Replace with your image path
    date: "August 25, 2023",
  },
  // Add more blog data as needed
];
const Blog = () => {
  return (
    <div className="container mx-auto py-8">
      <h1 className="text-3xl font-semibold mb-4">Latest Blog Posts</h1>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
        {blogData.map((blog, index) => (
          <Blogs
            key={blog.id}
            id={blog.id}
            title={blog.title}
            description={blog.description}
            imageUrl={blog.imageUrl}
            date={blog.date}
          />
        ))}
      </div>
    </div>
  );
};

export default Blog;
